spring.application.name: model-ms
spring.profiles.active: ${PROFILE:local}

server.port: ${SERVER_PORT:3042}

info:
  app.name: ${spring.application.name}
  app.version: ${version:project.version}
  app.profile: ${spring.profiles.active}

management:
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: health,info
  health.mongo.enabled: false

management.info:
  build.enabled: true
  env.enabled: true
  java.enabled: true
  os.enabled: true

logging.level:
  org.springframework: INFO
  org.springframework.web: INFO

spring.cloud.stream:
  default:
    binder: rabbit
    contentType: application/json

spring.cloud.stream.bindings:
  iotData-in-0:
    destination: iot.data

spring.cloud.stream.rabbit.bindings:
  iotData-in-0:
    consumer:
      autoBindDlq: false
